### ISSUE TITLE
Add demo URL

### ISSUE THREAD

**Issue by sebdeckers** [caalberts/scrabble#23]
The `README.md` is great. Don't forget to add a URL to the playable demo.
- [x] Add URL to `README.md`
- [x] Add URL to GitHub repo description. Click _Edit_ on the [repo homepage](https://github.com/caalberts/scrabble) to see the URL field.

**Comment by caalberts** [comment]
The screenshot links to the demo. I Guess I need to make it more obvious

**Comment by sebdeckers** [comment]
Ah, I think I did not expect to find the link there because images on GitHub READMEs by default link to the image file itself.
